displaytrigger_host: localhost
artnet_dmx_host: 192.168.0.111
framerate: 30.0
scaninterval: 0
postmortem: False
log_level: 20
path_sequences: data/sequences
path_stage_description: data/stageDescription/simple.yaml
