displaytrigger_host: localhost

framerate: 30.0
scaninterval: 0

#path_media: /srv/media/
#http_png_port: 23487

path_sequences: data/sequences
path_stage_description: data/stageDescription/superLimitBreak2019.yaml

dmx_host: 192.168.0.111
dmx_mapping: data/stageDescription/superLimitBreak2019.dmx.yaml

output_mode: json_single_triggers
postmortem: False
log_level: 20