subscriptionserver_uri: ws://localhost:9873
media_url: http://localhost/media/
mediainfo_url: http://localhost/mediainfo/

framerate: 30
scaninterval: 1

path_sequences: data/sequences
path_stage_description: data/stageDescription/superLimitBreak2019.yaml

dmx_host: localhost
dmx_mapping: data/stageDescription/superLimitBreak2019.dmx.yaml

http_png_port: 23487

output_mode: json_state_continuous
postmortem: True
log_level: 10