version: '3.6'

# NOTE
# This is to be combined with other `displayTrigger` containers
# It is used by `systemSetup`

services:
  stage_orchestration:
    image: superlimitbreak/stageorchestration
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/stageOrchestration:ro
    ports:
      - 23487:23487
    links:
      -
    command: --config config.docker.yaml --displaytrigger_host subscriptionserver --mediainfo_host mediainfoservice
