version: '3.6'

# NOTE
# This is to be combined with other `displayTrigger` containers
# It is used by `systemSetup`

services:
  stage_orchestration:
    image: superlimitbreak/stageorchestration:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/stageOrchestration:ro
    ports:
      - 23487:23487
    links:
      -
    command: --config config.docker.yaml --subscriptionserver_host subscriptionserver --media_url http://displaytrigger/media/ --mediainfo_url http://mediainfoservice:8331/
